cabal-version: 2.4
name: stockquotes
version: 0.0.1
synopsis: Stockquotes processes historical stock quotes data.
build-type: Simple 

executable stockquotes
    hs-source-dir: stockquotes
    main-is: Main.hs
    other-modules: Param QuoteData StatReport Charts HtmlReport
    build-depends:
        base
    default-language: Haskell2010